package graphic

import (
	"projet/ascii"
	"projet/utils"
	"projet/values"
	"strconv"
)

func DisplayInventory() {
	utils.ClearTerminal()

	utils.Writeln("")
	utils.Writeln("")
	utils.Writeln(ascii.MenuDogsTitle)

	utils.Writeln(utils.CenterText("======== Inventaire =======", 75))
	switch values.CurrentOption {
	case 0:
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Heal)+"] Heal               |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 1:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Poison)+"] Poison             |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 2:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.WriteColor(utils.CenterText("> Kalashnikov             |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 3:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Fireball)+"] Fireball           |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 4:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Iceball)+"] Iceball            |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 5:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Bomb)+"] Bomb               |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 6:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Shield)+"] Shield             |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 7:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Heineken)+"] Heineken           |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 8:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Wood)+"] Bois               |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 9:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Viscous)+"] Vis                |", 75), "yellow")
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 10:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.WriteColor(utils.CenterText("> x["+strconv.Itoa(values.Player.Inventory.Stone)+"] Pierre             |", 75), "yellow")
		utils.Writeln(utils.CenterText("| Retour                  |", 75))
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	case 11:
		utils.Writeln(utils.CenterText("| x%d Heal               |", 75), values.Player.Inventory.Heal)
		utils.Writeln(utils.CenterText("| x%d Poison             |", 75), values.Player.Inventory.Poison)
		utils.Writeln(utils.CenterText("| x%t Kalashnikov     |", 75), values.Player.Inventory.Kalashnikov)
		utils.Writeln(utils.CenterText("| x%d Fireball           |", 75), values.Player.Inventory.Fireball)
		utils.Writeln(utils.CenterText("| x%d Iceball            |", 75), values.Player.Inventory.Iceball)
		utils.Writeln(utils.CenterText("| x%d Bomb               |", 75), values.Player.Inventory.Bomb)
		utils.Writeln(utils.CenterText("| x%d Shield             |", 75), values.Player.Inventory.Shield)
		utils.Writeln(utils.CenterText("| x%d Heineken           |", 75), values.Player.Inventory.Heineken)
		utils.Writeln(utils.CenterText("| x%d Bois               |", 75), values.Player.Inventory.Wood)
		utils.Writeln(utils.CenterText("| x%d Vis                |", 75), values.Player.Inventory.Viscous)
		utils.Writeln(utils.CenterText("| x%d Pierre             |", 75), values.Player.Inventory.Stone)
		utils.WriteColor(utils.CenterText("> Retour                  |", 75), "yellow")
		utils.Writeln(utils.CenterText("===========================", 75))
		break
	}
}
